---
title: "DM-assignment"
author: "Leo Song"
date: "2024-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Validation_Analysis/data_validation.R")
```


```{r}
library(RSQLite)
conn <- dbConnect(RSQLite::SQLite(), dbname = "DM_assignment.db")


# Create seller table
dbExecute(conn, 'CREATE TABLE if not exists seller (
          seller_id VARCHAR(255)  PRIMARY KEY, 
          seller_name VARCHAR(255) NOT NULL, 
          seller_email VARCHAR(255) NOT NULL UNIQUE,  
          seller_city VARCHAR(100), seller_country VARCHAR(100),
          seller_phone_no VARCHAR(20)
          )')

# Create product table
dbExecute(conn, 'CREATE TABLE if not exists product (
          product_id VARCHAR(255)  PRIMARY KEY, 
          category_id VARCHAR(255)  NOT NULL, 
          seller_id VARCHAR(255)  NOT NULL, 
          product_name VARCHAR(255) NOT NULL, 
          product_desc TEXT,
          product_price DECIMAL(10, 2) NOT NULL, 
          quantity_available INT NOT NULL, 
          FOREIGN KEY (category_id) REFERENCES categories(category_id), 
          FOREIGN KEY (seller_id) REFERENCES seller(seller_id)
          )')

# Create customers table
dbExecute(conn, 'CREATE TABLE if not exists customer (
          customer_id VARCHAR(255)  PRIMARY KEY, 
          cust_password VARCHAR(255) NOT NULL, 
          email VARCHAR(255) NOT NULL UNIQUE, 
          first_name VARCHAR(100) NOT NULL, 
          last_name VARCHAR(100) NOT NULL, 
          date_of_birth DATE, 
          gender CHAR(1), 
          street VARCHAR(255), 
          house_number VARCHAR(50), 
          city VARCHAR(100), 
          country VARCHAR(100), 
          phone_number VARCHAR(20)
          )')

# Create categories table
dbExecute(conn, 'CREATE TABLE if not exists category (
          category_id VARCHAR(255)  PRIMARY KEY, 
          category_name VARCHAR(255) NOT NULL, 
          category_desc TEXT
          )')

# Create product_payment_relationship
dbExecute(conn, 'CREATE TABLE IF NOT EXISTS product_payment_relationship (
          product_id VARCHAR(255),
          payment_id VARCHAR(255),
          quantity INT NOT NULL,
          PRIMARY KEY (product_id, payment_id),
          FOREIGN KEY (product_id) REFERENCES product(product_id),
          FOREIGN KEY (payment_id) REFERENCES payment(payment_id)
          )')




# Create payment table
dbExecute(conn, 'CREATE TABLE if not exists payment (
          payment_id VARCHAR(255) PRIMARY KEY, 
          customer_id VARCHAR(255),
          payment_type VARCHAR(50), 
          payment_status VARCHAR(50), 
          date_time DATETIME,
          card_number VARCHAR(20),
          FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
          )')


#CREATE customers_review_products_relationship TABLE
dbExecute(conn, 'CREATE TABLE if not exists customers_review_products_relationship (
          customer_id VARCHAR(255) NOT NULL,
          product_id VARCHAR(255) NOT NULL,
          comment TEXT,
          rating INT NOT NULL,
          date_time DATETIME,
          PRIMARY KEY (customer_id, product_id),
          FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
          FOREIGN KEY (product_id) REFERENCES product(product_id)
           )')

# List all tables in the database connection
tables <- dbListTables(conn)

#  close the database connection 
dbDisconnect(conn)

```

```{r get all ID}
library(DBI)
library(stringi)
library(RSQLite)
library(dplyr)

# Function to generate unique IDs with a specific word and fixed length
generate_unique_ids_with_prefix <- function(n, word,lenOfId) {
  unique_ids <- character(n)
  # Loop through the number of IDs we need to generate
  for (i in 1:n) {
    is_unique <- FALSE  # Initialize a flag to check uniqueness
    while (!is_unique) {
      # Generate a 6-character random alphanumeric string
      random_string <- stri_rand_strings(1, lenOfId-4, pattern = "[a-zA-Z0-9]")
      full_id <- paste0(word, random_string)
      # Check if this ID is already in our list of unique IDs
      if (!full_id %in% unique_ids) {
        unique_ids[i] <- full_id  # If unique, add it to the list
        is_unique <- TRUE  # Set the flag to true to exit the loop
      }
    }
  }
  return(unique_ids)
}

# Set a seed for reproducibility
set.seed(1234)  
# Assuming n_sellers, n_customers, n_categories, n_products are predefined
n_sellers <- nrow(read.csv("data_file/seller.csv"))
n_customers <- nrow(read.csv("data_file/customer.csv"))
n_categories <- nrow(read.csv("data_file/categories.csv"))
n_products <- nrow(read.csv("data_file/products.csv"))
n_payments <- nrow(read.csv("data_file/payment.csv"))



# Example usage for 5 Seller IDs
seller_ids <- generate_unique_ids_with_prefix(n_sellers, "selr_",10)

customer_ids <- generate_unique_ids_with_prefix(n_customers, "cust_",10)

category_ids <- generate_unique_ids_with_prefix(n_categories, "catg_",10)

product_ids <- generate_unique_ids_with_prefix(n_products, "prod_",10)

payment_ids <- generate_unique_ids_with_prefix(n_payments, "pytm_",10)

```

```{r prepare data}


seller_data <- read.csv("data_file/seller.csv")
seller_data$seller_id<-seller_ids


# Change the column name from 'seller_state' to 'seller_country'
names(seller_data)[names(seller_data) == "seller_state"] <- "seller_country"

customer_data <- read.csv("data_file/customer.csv")
customer_data$customer_id<-customer_ids
# check whether email is unique
unique_email_count <- length(unique(customer_data$email))# email is unique
customer_review_product_relationship<-read.csv("data_file/reviews.csv")



# Generate all possible combinations of product_id and customer_id
combinations <- expand.grid(product_id = product_ids, customer_id = customer_ids)

# Ensure there are enough combinations to satisfy the number of rows in reviews.csv
if (nrow(customer_review_product_relationship) <= nrow(combinations)) {
  # Randomly select from all unique combinations
  selected_combinations <- combinations[sample(nrow(combinations), size = nrow(customer_review_product_relationship), replace = FALSE), ]
  
  # Assign product_id and customer_id to customer_review_product_relationship
  customer_review_product_relationship$product_id <- selected_combinations$product_id
  customer_review_product_relationship$customer_id <- selected_combinations$customer_id
} else {
  # If there are not enough combinations, print an error or warning
  print("Not enough unique combinations of product_id and customer_id to assign to each row.")
}
# Check for duplicates based on 'product_id' and 'customer_id'
duplicates <- duplicated(customer_review_product_relationship[c("product_id", "customer_id")])
# Count the number of duplicates
num_duplicates <- sum(duplicates)

# Print the number of duplicate rows found
print(paste("Number of duplicate rows:", num_duplicates))


category_data<-read.csv("data_file/categories.csv")
category_data$category_id_new<-category_ids

product_data<-read.csv("data_file/products.csv")
# Assuming product_data and category_data are already loaded into your R environment

# Perform a left join to match each product with its corresponding category,
# and then select the new category ID to replace the old one.
product_data_updated <- product_data %>%
  left_join(category_data, by = "category_id") %>%
  mutate(category_id = category_id_new) %>%
  select(-category_id_new) # Assuming you want to remove the 'category_id_new' column after update

# Now, product_data_updated contains products with their category IDs updated to category_id_new where applicable

product_data$category_id<-product_data_updated$category_id
product_data$seller_id<- sample(seller_ids, size = nrow(product_data), replace = TRUE)
product_data$product_id<- product_ids
#change  category id
category_data$category_id<-category_ids
category_data <- subset(category_data, select = -category_id_new)


payment_data<-read.csv("data_file/payment.csv")
payment_data$payment_id<-payment_ids


payment_data$customer_id<-sample(customer_ids, size = nrow(payment_data), replace = TRUE)
#load Product_payment_relationship
Product_payment_relationship_data <- read.csv("data_file/is_in.csv")
# Generate all possible combinations of product_id and payment_id
#
payment_id_filter <- payment_data %>%
  filter(payment_status %in% c("Success", "Pending")) %>%
  select(payment_id)
product_id_filter<-product_ids[1:50]
product_id_new<-product_ids[51:94]


# Step 1: Randomly assign a product_id from product_id_filter to each payment_id
set.seed(123) # Ensure reproducibility of the results
initial_assignments <- payment_id_filter %>%
  mutate(product_id = sample(product_id_filter, size = n(), replace = TRUE))

# Step 2: Generate all possible combinations of product_id_new and payment_id_filter, then randomly select 111 combinations
all_new_combinations <- expand.grid(product_id = product_id_new, payment_id = payment_id_filter$payment_id)
set.seed(124) # Change seed for diversity in randomness
additional_assignments <- all_new_combinations %>%
  sample_n(111)

# Step 3: Combine the two parts into a single dataframe
final_assignments <- rbind(initial_assignments, additional_assignments)


  # Assign product_id and payment_id to Product_payment_relationship_data
  Product_payment_relationship_data$product_id <- final_assignments$product_id
  Product_payment_relationship_data$payment_id <- final_assignments$payment_id

# Check for duplicates based on 'product_id' and 'payment_id'
duplicates <- duplicated(Product_payment_relationship_data[c("product_id", "payment_id")])

# Count the number of duplicates
num_duplicates <- sum(duplicates)

# Print the number of duplicate rows found
print(paste("Number of duplicate rows:", num_duplicates))

```









```{r dataValidation}
checkValidation(seller_data, customer_data, category_data, product_data,payment_data, customer_review_product_relationship,Product_payment_relationship_data)
```


