name: Data Operations and Analysis Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Runs every day at 00:00
    - cron: '0 0 * * *'

jobs:
  data-operations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up R env
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.0'

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
        restore-keys: |
            ${{ runner.os }}-r-


# Installing the necessary Packages  
    - name: Install R packages
      run: Rscript -e 'install.packages(c("DBI", "RSQLite", "ggplot2", "lubridate"), dependencies = TRUE)'


# Providing the link to file to execute
    - name: Run data validation script
      run: <link>data_validation.R
    - name: Update database with new data
      run: <link>Rscript path/to/your/update_database.R
    - name: Run basic data analysis
      run: <link>Rscript path/to/your/data_analysis.R


# Commit changes
    - name: Add and commit changes
      run: |
        git config --global user.email "raschoudhary879@gmail.com"
        git config --global user.name "Anand7Choudhary"
        git add -f path/to/your/database_file.db path/to/other/modified/files
        git commit -m "Update database and analysis results" || echo "No changes to commit"
        
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
